/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author #EK
 */
public class FRMMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public FRMMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskprincipal = new javax.swing.JDesktopPane();
        mbarprincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitemcli = new javax.swing.JMenuItem();
        mitempro = new javax.swing.JMenuItem();
        mnusair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout deskprincipalLayout = new javax.swing.GroupLayout(deskprincipal);
        deskprincipal.setLayout(deskprincipalLayout);
        deskprincipalLayout.setHorizontalGroup(
            deskprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        deskprincipalLayout.setVerticalGroup(
            deskprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        mitemcli.setText("Clientes");
        mitemcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemcliActionPerformed(evt);
            }
        });
        jMenu1.add(mitemcli);

        mitempro.setText("Produto");
        mitempro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemproActionPerformed(evt);
            }
        });
        jMenu1.add(mitempro);

        mbarprincipal.add(jMenu1);

        mnusair.setText("Sair");
        mnusair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TESTE(evt);
            }
        });
        mbarprincipal.add(mnusair);

        setJMenuBar(mbarprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskprincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemcliActionPerformed
        // TODO add your handling code here:
        
           FRMListaCliente listcliente = new FRMListaCliente();
           
           deskprincipal.add(listcliente);
           listcliente.setVisible(true);

   // try {
     //   cadascliente.setMaximum(true);
    //} catch (Exception e) {
    //}
    
    }//GEN-LAST:event_mitemcliActionPerformed

    private void TESTE(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TESTE
        // TODO add your handling code here:
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja sair do sistema?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            this.dispose();
        }

    }//GEN-LAST:event_TESTE

    private void mitemproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemproActionPerformed
        // TODO add your handling code here:
         FRMListaProduto listproduto = new FRMListaProduto();
           
           deskprincipal.add(listproduto);
           listproduto.setVisible(true);
    }//GEN-LAST:event_mitemproActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskprincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mbarprincipal;
    private javax.swing.JMenuItem mitemcli;
    private javax.swing.JMenuItem mitempro;
    private javax.swing.JMenu mnusair;
    // End of variables declaration//GEN-END:variables
}
